account-mgmt:
  identity:
    server: ${IDENTITY_SERVER}
    scim2:
      users: "/scim2/Users"
    mgt-user:
      id: ${IDENTITY_MGT_USER_ID}
      password: ${IDENTITY_MGT_USER_PASSWORD}
  configuration:
    activation:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/active
      expire-period-days: 10
      email-subject: "Kích hoạt tài khoản đăng ký"
    invitation:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/register
  bitly: 
    name: bit.ly
    server: https://api-ssl.bitly.com
    shorten-link: /v4/shorten
    token: ${BITLY_ACCESS_TOKEN}
