account-mgmt:
  configuration:
    activation:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/active
      expire-period-days: 10
      expire-period-duration: "PT10M"
      email-subject: "Kích hoạt tài khoản đăng ký"
    invitation:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/register
    reset-password:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/reset-password
  bitly:
    name: bit.ly
    server: https://api-ssl.bitly.com
    shorten-link: /v4/shorten
    token: ${BITLY_ACCESS_TOKEN}
