account-mgmt:
  datasource:
    mongoProperties:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
      uri: ${DATABASE_CONNECTION_URI}
      database: ${DATABASE_NAME}
  identity:
    server: ${IDENTITY_SERVER}
    scim2:
      users: "/scim2/Users"
    mgt-user:
      id: ${IDENTITY_MGT_USER_ID}
      password: ${IDENTITY_MGT_USER_PASSWORD}
  configuration:
    activation:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/register
      expire-period-days: 10
      email-subject: "Kích hoạt tài khoản đăng ký"
    invitation:
      default-link: https://app-profile-dev.hungthinhcorp.com.vn/account/active

