profile-mgmt:
  identity:
    server: ${IDENTITY_SERVER}
    scim2:
      users: "/scim2/Users"
    mgt-user:
      id: ${IDENTITY_MGT_USER_ID}
      password: ${IDENTITY_MGT_USER_PASSWORD}
feign:
  okhttp:
    enabled: true