server:
  port: 8080
  error:
    include-stacktrace: on_trace_param
spring:
  profiles:
    include:
      - 'profile'
      - 'account-mgmt'
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      auto-index-creation: true
      uri: ${DATABASE_CONNECTION_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://htid.hungthinhcorp.com.vn/oauth2/jwks
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        security: DEBUG
springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    path: /api-docs

profile:
  web-client: https://app-profile-dev.hungthinhcorp.com.vn
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: "Customer"
