#server:
#  port: 8081
#  servlet:
#    context-path: /resource-server-jwt
#server:
#  port: 443
#  ssl:
#    key-store: classpath:ssl-server.jks
#    key-store-password: changeit
#    keyStoreType: JKS
#    keyAlias: selfsigned_localhost_sslserver
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://localhost:9443/oauth2/token
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://htid.hungthinhcorp.com.vn/oauth2/token
