#server:
#  port: 8081
#  servlet:
#    context-path: /resource-server-jwt
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://htid.hungthinhcorp.com.vn/oauth2/token
