server:
  port: 8082
security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://localhost:9443/oauth2/jwks
spring:
  data:
    mongodb:
      host: localhost
      database: profile_db
      port: 27017
      username: htuser
      password: hungthinh123
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:9443/oauth2/jwks
logging:
  level:
    org:
      springframework:
        security: DEBUG
